### ISSUE TITLE
.NET 8 Support

### ISSUE THREAD

**Issue by Pacman1988** [StefH/Blazor.WebAssembly.Authentication.Auth0#11]
The package currently does not allow for .NET 8 support. It instead throws an NU1608 error. The project needs to be updated to support targeting the right references for the right versions.

_Project.csproj: [NU1608] Detected package version outside of dependency constraint: WebAssembly.Authentication.Auth0 1.2.0 requires Microsoft.AspNetCore.Components.WebAssembly.Authentication (>= 7.0.0 && < 8.0.0) but version Microsoft.AspNetCore.Components.WebAssembly.Authentication 8.0.3 was resolved._

**Comment by StefH** [comment]
@Pacman1988 
Can you check if the PR (#12) does fix your issue?

**Comment by Pacman1988** [comment]
@StefH 
On my quick tests it looks good and the warning is gone.

**Comment by StefH** [comment]
A new NuGet will be released soon.
