### ISSUE TITLE
.net 5 support

### ISSUE THREAD

**Issue by valerii-sovytskyi** [StefH/Blazor.WebAssembly.Authentication.Auth0#3]
Failed to run Azure Pipelines as it requires this package to be supported for .net 5

`##[error]The nuget command failed with exit code(1) and error(NU1202: Package WebAssembly.Authentication.Auth0 1.0.0.1 is not compatible with net50 (.NETFramework,Version=v5.0). Package WebAssembly.Authentication.Auth0 1.0.0.1 supports: netstandard2.1 (.NETStandard,Version=v2.1)
NU1202: Package WebAssembly.Authentication.Auth0 1.0.0.1 is not compatible with net50 (.NETFramework,Version=v5.0) / browser-wasm. Package WebAssembly.Authentication.Auth0 1.0.0.1 supports: netstandard2.1 (.NETStandard,Version=v2.1)
Errors in D:\a\1\s\FinanceManager.Client\FinanceManager.Client.csproj
    NU1202: Package WebAssembly.Authentication.Auth0 1.0.0.1 is not compatible with net50 (.NETFramework,Version=v5.0). Package WebAssembly.Authentication.Auth0 1.0.0.1 supports: netstandard2.1 (.NETStandard,Version=v2.1)
    NU1202: Package WebAssembly.Authentication.Auth0 1.0.0.1 is not compatible with net50 (.NETFramework,Version=v5.0) / browser-wasm. Package WebAssembly.Authentication.Auth0 1.0.0.1 supports: netstandard2.1 (.NETStandard,Version=v2.1))
##[error]Packages failed to restore
`

**Comment by StefH** [comment]
https://github.com/StefH/Blazor.WebAssembly.Authentication.Auth0/pull/4

**Comment by StefH** [comment]
Hello @valerii-sovytskyi, thanks for noticing.

A new NuGet will be released shortly.
