### ISSUE TITLE
Broken on .NET 6.0

### ISSUE THREAD

**Issue by robertmclaws** [StefH/Blazor.WebAssembly.Authentication.Auth0#7]
### Problem
Microsoft has added an [AdditionalProviderParameters property to OidcProviderOptions](https://github.com/dotnet/aspnetcore/blob/c4f330d24eba97aeb354581a58466d065796baca/src/Components/WebAssembly/WebAssembly.Authentication/src/Options/OidcProviderOptions.cs#L68) in .NET 6.0. This creates a serializer conflict for anyone using this package and updating their project.

### Symptoms
You receive the following error message on Blazor app startup: `Unhandled exception rendering component: The JSON property name for 'Microsoft.AspNetCore.Components.WebAssembly.Authentication.Auth0ProviderOptions.AdditionalProviderParameters' collides with another property.`

### Solution
The code needs to be updated to exclude the old property from compilation on .NET 6.0 and later. I have prepared a pull request and will be submitting it shortly.

**Comment by StefH** [comment]
@robertmclaws 
Thanks for the PR.

I'll create a new version soon.
